name: Build and Release EXE

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --windowed --icon=icon.ico --name=SteamBoot main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: SteamBoot
          path: dist/SteamBoot.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
      - name: Download EXE artifact
        uses: actions/download-artifact@v3
        with:
          name: SteamBoot

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: SteamBoot.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
